### ISSUE TITLE
Documentation Non-Existant

### ISSUE THREAD

**Issue by ArchieHickmott** [ArchieHickmott/fortify-sql#1]
Documentation is a work in progress, I am working on it don't worry

**Comment by Helios-fr** [comment]
![regional-indicator-symbol-letter-o](https://github.com/Nerd-yee/quicksqlite-new/assets/79072303/818f655a-0ea7-47fd-932e-7d210333de39)
![regional-indicator-symbol-letter-k](https://github.com/Nerd-yee/quicksqlite-new/assets/79072303/1a760381-39aa-4849-9fb6-43ad5f38c687)

**Comment by ArchieHickmott** [comment]
Documentation is live in Documentation.html now
